spring.application.name=taskmanager
# Cloud MySQL Database Connection
spring.datasource.url=jdbc:mysql://root:SNSWkJtZzttjXtPrViYPOPBgtEcaKZRW@switchyard.proxy.rlwy.net:28799/railway

# Tell Spring to automatically create our tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL in the console
spring.jpa.show-sql=true